// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/version_simple_type.proto
// Protobuf Java Version: 4.26.1

package event-logging.v4.event_logging.v4;

public final class VersionSimpleTypeProto {
  private VersionSimpleTypeProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      VersionSimpleTypeProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*event_logging/v4/version_simple_type.p" +
      "roto\022\020event_logging.v4\032\033buf/validate/val" +
      "idate.proto*W\n\021VersionSimpleType\022#\n\037VERS" +
      "ION_SIMPLE_TYPE_UNSPECIFIED\020\000\022\035\n\031VERSION" +
      "_SIMPLE_TYPE_4_0_2\020\001B\337\001\n!event-logging.v" +
      "4.event_logging.v4B\026VersionSimpleTypePro" +
      "toP\001ZEgithub.com/gchq/event-logging-sche" +
      "ma/event_logging/v4;event_loggingv4\242\002\003EX" +
      "X\252\002\017EventLogging.V4\312\002\017EventLogging\\V4\342\002\033" +
      "EventLogging\\V4\\GPBMetadata\352\002\020EventLoggi" +
      "ng::V4b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    descriptor.resolveAllFeaturesImmutable();
    build.buf.validate.ValidateProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
